# Generated by Django 6.0.5 on 2026-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=50)),
            ],
        ),
    ]
