# Generated by Django 6.0.5 on 2026-05-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_students_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
