# Generated by Django 6.0.5 on 2026-05-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_student_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(default='City', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(default='course', max_length=50),
        ),
    ]
