# Generated by Django 6.0.5 on 2026-05-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_alter_student_age_alter_student_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
